# Gopkg.toml 
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

ignored = ["github.com/Azure/azure-service-bus-go"]

# Kubernetes incubator deps
[[constraint]]
  name = "github.com/kubernetes-incubator/custom-metrics-apiserver"
  revision = "3d9be26a50eb64531fc40eb31a5f3e6720956dc6" #revision number for 1.15.0 release

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "21.0.0"

[[override]]
  name = "github.com/emicklei/go-restful"
  version = "2.2.1"

[[override]]
  name = "github.com/emicklei/go-restful-swagger12"
  version = "1.0.1"

[[override]]
  name = "github.com/go-openapi/spec"
  revision = "1de3e0542de65ad8d75452a595886fdd0befb363"

[[override]]
  name = "github.com/spf13/cobra"
  revision = "c439c4fa093711d42e1b01acb1235b52004753c1"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.15"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.15"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.15"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-12.0"

[[constraint]]
  name = "k8s.io/metrics"
  branch = "release-1.15"

[prune]
  go-tests = true
  unused-packages = true