# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    branches:
      only:
        master
    docker:
      # specify the version
      - image: circleci/golang:1.10.3
         
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/jsturtevant/azure-k8-metrics-adapter
    steps:
      - checkout
      - setup_remote_docker
      - run: |  
          echo 'export VERSION="0.3.0-alpha.$CIRCLE_BUILD_NUM"' >> $BASH_ENV
      - run: |
          make build
      - run: |
          make push
  build-pr:
    branches:
      ignore:
        - master
    docker:
      # specify the version
      - image: circleci/golang:1.10.3
         
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/jsturtevant/azure-k8-metrics-adapter
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          make build
