apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
 name: pod-scaler
spec:
 scaleTargetRef:
   apiVersion: extensions/v1beta1
   kind: Deployment
   name: consumer
 minReplicas: 2
 maxReplicas: 10
 metrics:
  - type: External
    external:
      metricName: queue_messages_ready
      metricSelector:
        matchLabels:
          queue: worker_tasks
      targetValue: 30